### ISSUE TITLE
Infer alpha/beta/stable classifiers.

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#39] opened 2015-06-14 20:33 UTC
Based on the version number ?

0.0.x -> alpha
0.X.y -> Beta
X.y.z -> Stable

take care of devX suffixes ?

**Comment by takluyver** [comment] 2015-06-15 00:39
On reflection, I don't think this is worth it - those mappings are not very reliable, and I don't think there's a good stage to do it:

- I don't want to add classifiers when the user uploads - explicit is better than implicit, so all classifiers should be placed in flit.ini.
- But I don't want to set classifiers during `flit init` that need to change later by design, because it's annoying to have to remember to update it manually. Especially with these 'development status' classifiers, where there are no clear boundaries between one status and the next.

So closing for now. I think creating classifiers for things like Python version support (#38) is more reasonable, because that information is more likely to be stable.

**Closed by takluyver** 2015-06-15 00:39 UTC
