### ISSUE TITLE
flit install on self fails

### ISSUE THREAD

**Issue by dsblank** [takluyver/flit#48] opened 2015-08-20 13:13 UTC
I'm getting an error (flit installed from pip3) on flit's install with:

```bash
$ flit install
Installing requirements                                                                                                 I-flit.install
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", 'pexpect>=3.3;', 'at', ';')

Storing debug log for failure in /home/dblank/.pip/pip.log
Traceback (most recent call last):
  File "/usr/local/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/flit/__init__.py", line 75, in main
    Installer(args.ini_file, user=args.user, symlink=args.symlink, deps=args.deps).install()
  File "/usr/local/lib/python3.4/dist-packages/flit/install.py", line 176, in install
    self.install_requirements()
  File "/usr/local/lib/python3.4/dist-packages/flit/install.py", line 158, in install_requirements
    check_call(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '--user', '-r', '/tmp/tmpr1zrx823requirements.txt']' returned non-zero exit status 2
```

**Comment by dsblank** [comment] 2015-08-20 13:27
The `check_call(cmd)` is failing on /tmp/requirements.txt files that look like:

```
metakernel>=0.9;
```

with no line ending.

**Comment by takluyver** [comment] 2015-08-24 18:14
I can't reproduce - maybe it depends on the version of pip - but I think #49 should fix it. Can you test and let me know?

**Comment by dsblank** [comment] 2015-08-25 08:30
That gave a different error (below), but updating pip fixed the issues.

I was using pip 6.1.1, now 7.1.2.

Thanks!

```bash
$ flit install
Installing requirements                                                                                          I-flit.install
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'requests;', 'at', ';')

Storing debug log for failure in /home/dblank/.pip/pip.log
Traceback (most recent call last):
  File "/usr/local/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/home/dblank/.local/lib/python3.4/site-packages/flit/__init__.py", line 75, in main
  File "/home/dblank/.local/lib/python3.4/site-packages/flit/install.py", line 161, in install
  File "/home/dblank/.local/lib/python3.4/site-packages/flit/install.py", line 143, in install_requirements
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '--user', '-r', '/tmp/tmpm5zjegfyrequirements.txt']' returned non-zero exit status 2
```

**Comment by takluyver** [comment] 2015-08-25 16:13
OK, closing that on the grounds that we appear to need pip 7 anyway.

**Comment by takluyver** [comment] 2016-08-12 13:55
I said 'closing' but failed to hit close, it seems.

**Closed by takluyver** 2016-08-12 13:55 UTC
